---
dependency:
  enabled: false
driver:
  name: docker
platforms:
  - name: buster
    image: library/debian:buster
lint: |
  set -e
  yamllint -c molecule/default/.yamllint .
  ansible-lint --exclude molecule/ --exclude library/
  flake8 --exclude roles,molecule,library
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
